def reccomender(object,para,color)
  if object=="corsage"&&para=="mom"&&color=="girly"
    url="https://www.etsy.com/listing/238062179/baby-shower-mommy-to-be-corsage-girl?ref=related-3"
    pic1="https://img1.etsystatic.com/065/1/7037722/il_570xN.791641225_dmkz.jpg"
  elsif object=="corsage"&&para=="mom"&&color=="boyish"  
    pic1="https://img0.etsystatic.com/105/0/7037722/il_570xN.988074888_n6lm.jpg"
    url="https://www.etsy.com/listing/220549473/baby-co-baby-shower-mom-to-be-corsage?ref=shop_home_active_24"
  elsif object=="corsage"&&para=="mom"&&color=="pastel"  
    pic1="https://img1.etsystatic.com/056/1/7037722/il_570xN.754465063_q0o1.jpg"
    url=" https://www.etsy.com/listing/204581719/baby-shower-mom-corsage-pastel-colors?ref=shop_home_active_35"
  elsif object=="corsage"&&para=="mom"&&color=="bright"  
    pic1="https://img0.etsystatic.com/064/0/7037722/il_570xN.791878598_cd0m.jpg"
    url="https://www.etsy.com/listing/238061445/safari-baby-shower-mom-to-be-corsage-boy?ref=shop_home_active_40"
  elsif object=="corsage"&&para=="dad"&&color=="girly"  
    pic1="https://img1.etsystatic.com/109/0/7037722/il_570xN.1009375617_ozgb.jpg"
    url="https://www.etsy.com/listing/267842032/pink-and-gray-elephant-baby-shower-daddy?ref=shop_home_active_19"     
  elsif object=="corsage"&&para=="dad"&&color=="boyish"  
    pic1="https://img1.etsystatic.com/141/0/7037722/il_570xN.1171695361_mtfv.jpg"
    url="https://www.etsy.com/listing/232217800/baby-co-baby-shower-daddy-to-be-pin-baby?ref=related-8"
  elsif object=="corsage"&&para=="dad"&&color=="pastel"  
    pic1="https://img1.etsystatic.com/112/0/7037722/il_570xN.1009375623_48ut.jpg"
    url="https://www.etsy.com/listing/267842032/pink-and-gray-elephant-baby-shower-daddy?ref=shop_home_active_19"
  elsif object=="corsage"&&para=="dad"&&color=="bright"  
    pic1="https://img1.etsystatic.com/109/0/7037722/il_570xN.866580337_14cm.jpg"
    url="https://www.etsy.com/listing/204877078/daddy-to-be-cowboy-corsage-western-baby?ref=shop_home_active_16"
  elsif object=="corsage"&&para=="n/a"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="corsage"&&para=="n/a"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"   
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="corsage"&&para=="n/a"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png" 
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="corsage"&&para=="n/a"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="n/a"&&color=="girly"
    pic1="https://img1.etsystatic.com/028/0/7037722/il_570xN.660330447_iafq.jpg"      
    url="https://www.etsy.com/listing/205303405/diaper-cake-centerpiece-pink-and-lime?ref=shop_home_active_1"
 elsif object=="dipercake"&&para=="n/a"&&color=="boyish"
    pic1="https://img1.etsystatic.com/134/2/7037722/il_570xN.1099704867_nhae.jpg" 
    url="https://www.etsy.com/listing/482396447/blue-and-white-diaper-cake-baby-shower?ref=related-3"
 elsif object=="dipercake"&&para=="n/a"&&color=="pastel"
    pic1="https://img1.etsystatic.com/028/0/7037722/il_570xN.660330447_iafq.jpg"      
    url="https://www.etsy.com/listing/205303405/diaper-cake-centerpiece-pink-and-lime?ref=related-1"
 elsif object=="dipercake"&&para=="n/a"&&color=="bright"
    pic1="https://img0.etsystatic.com/043/0/7037722/il_570xN.645832756_do2o.jpg"   
    url="https://www.etsy.com/listing/201429034/boy-baby-shower-diaper-cake-centerpiece?ref=related-1"
 elsif object=="dipercake"&&para=="mom"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"   
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="mom"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"   
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="mom"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"   
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="mom"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
elsif object=="dipercake"&&para=="dad"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="dad"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
elsif object=="dipercake"&&para=="dad"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="dipercake"&&para=="dad"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
elsif object=="topper"&&para=="n/a"&&color=="girly"
    pic1="https://img1.etsystatic.com/048/0/7037722/il_570xN.733677735_ii8j.jpg" 
    url="https://www.etsy.com/listing/223987688/14-gold-crown-cupcake-topper-food-picks?ref=shop_home_active_4"
 elsif object=="topper"&&para=="n/a"&&color=="boyish"
    pic1="https://img0.etsystatic.com/133/0/7037722/il_570xN.996699584_8847.jpg" 
    url="https://www.etsy.com/listing/280406698/cowboy-cake-topper-boot-hat-and-rope?ref=related-1"
 elsif object=="topper"&&para=="n/a"&&color=="pastel"
    pic1="https://img0.etsystatic.com/075/0/7037722/il_570xN.817640572_hhmy.jpg" 
    url="https://www.etsy.com/listing/246366975/6in-metal-eiffel-tower-centerpice-paris?ref=related-4"
 elsif object=="topper"&&para=="n/a"&&color=="bright"
    pic1="https://img1.etsystatic.com/134/1/7037722/il_570xN.1044223747_8y78.jpg"
    url="https://www.etsy.com/listing/462122377/stork-baby-shower-cake-topper-boy-baby?ref=related-2"
  elsif object=="topper"&&para=="mom"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="topper"&&para=="mom"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="topper"&&para=="mom"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="topper"&&para=="mom"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="topper"&&para=="dad"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="topper"&&para=="dad"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="topper"&&para=="dad"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"   
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="topper"&&para=="dad"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="centerpiece"&&para=="n/a"&&color=="girly"
    pic1="https://img0.etsystatic.com/136/1/7037722/il_570xN.1000244390_5t9k.jpg"
    url="https://www.etsy.com/listing/249881261/paris-baby-shower-favors-bags-organza?ref=shop_home_active_57"
 elsif object=="centerpiece"&&para=="n/a"&&color=="boyish"
    pic1="https://img1.etsystatic.com/025/0/7037722/il_570xN.637890961_4jcv.jpg"
    url="https://www.etsy.com/listing/199249908/blue-baby-shower-favor-boxes-set-of-12?ref=related-1"
 elsif object=="centerpiece"&&para=="n/a"&&color=="pastel"
    pic1="https://img0.etsystatic.com/107/0/7037722/il_570xN.1009096332_2p6t.jpg"
    url="https://www.etsy.com/shop/CutestFavors/items"
 elsif object=="centerpiece"&&para=="n/a"&&color=="bright"
    pic1="https://img0.etsystatic.com/055/0/7037722/il_570xN.685857460_gt8y.jpg"
    url="https://www.etsy.com/shop/CutestFavors/items"
 elsif object=="centerpiece"&&para=="mom"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="centerpiece"&&para=="mom"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="centerpiece"&&para=="mom"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="centerpiece"&&para=="mom"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="centerpiece"&&para=="dad"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="centerpiece"&&para=="dad"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="centerpiece"&&para=="dad"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="centerpiece"&&para=="dad"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="pins"&&para=="n/a"&&color=="girly"
    pic1="https://img1.etsystatic.com/038/0/7037722/il_570xN.634906187_lbe3.jpg"
    url="https://www.etsy.com/listing/198437749/baby-shower-guest-corsages-gender-reveal?ref=shop_home_active_49"
  elsif object=="pins"&&para=="n/a"&&color=="boyish"
    pic1="https://img1.etsystatic.com/032/0/7037722/il_570xN.634164855_hjen.jpg"
    url="https://www.etsy.com/listing/198235644/stork-baby-shower-white-and-blue-baby?ref=shop_home_active_7"
  elsif object=="pins"&&para=="n/a"&&color=="pastel"
    pic1="https://img0.etsystatic.com/054/0/7037722/il_570xN.740726386_fje1.jpg"
    url="https://www.etsy.com/shop/CutestFavors/items"
  elsif object=="pins"&&para=="n/a"&&color=="bright"
    pic1="https://img0.etsystatic.com/049/0/7037722/il_570xN.678474120_l6az.jpg"
    url="https://www.etsy.com/listing/210121218/bow-baby-shower-guest-pins-pink-and?ref=shop_home_active_34"
  elsif object=="pins"&&para=="mom"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="pins"&&para=="mom"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="pins"&&para=="mom"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="pins"&&para=="mom"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  elsif object=="pins"&&para=="dad"&&color=="girly"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="pins"&&para=="dad"&&color=="boyish"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
 elsif object=="pins"&&para=="dad"&&color=="pastel"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"    
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
  else object=="pins"&&para=="dad"&&color=="bright"
    pic1="http://www.freeiconspng.com/uploads/error-icon-28.png"
    url="https://www.etsy.com/shop/CutestFavors?ref=listing-shop2-all-items-count#items"
     end
  [pic1, url]
end